package it.polito.dp2.TAMELESS.sol.db;

public enum TypeOfData {
	ENTITY,
	THREAT,
	RELATION_2ENTITIES,
	RELATION_3ENTITIES,
	RELATION_2ENTITIES_1THREAT,
	RELATION_1ENTITY_1THREAT,
	PROPERTY_1ENTITY,
	PROPERTY_1ENTITY_1THREAT,
	DERIVED_PROPERTY_1ENTITY,
	DERIVED_PROPERTY_1ENTITY_1THREAT
}
