//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.01 at 04:03:41 PM CEST 
//


package it.polito.dp2.TAMELESS.sol.service.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.TAMELESS.sol.service.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.TAMELESS.sol.service.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Properties1Entity1Threat }
     * 
     */
    public Properties1Entity1Threat createProperties1Entity1Threat() {
        return new Properties1Entity1Threat();
    }

    /**
     * Create an instance of {@link Property1Entity1Threat }
     * 
     */
    public Property1Entity1Threat createProperty1Entity1Threat() {
        return new Property1Entity1Threat();
    }

    /**
     * Create an instance of {@link Relations2Entities1Threat }
     * 
     */
    public Relations2Entities1Threat createRelations2Entities1Threat() {
        return new Relations2Entities1Threat();
    }

    /**
     * Create an instance of {@link Relation2Entities1Threat }
     * 
     */
    public Relation2Entities1Threat createRelation2Entities1Threat() {
        return new Relation2Entities1Threat();
    }

    /**
     * Create an instance of {@link Relations3Entities }
     * 
     */
    public Relations3Entities createRelations3Entities() {
        return new Relations3Entities();
    }

    /**
     * Create an instance of {@link Relation3Entities }
     * 
     */
    public Relation3Entities createRelation3Entities() {
        return new Relation3Entities();
    }

    /**
     * Create an instance of {@link Property1Entity }
     * 
     */
    public Property1Entity createProperty1Entity() {
        return new Property1Entity();
    }

    /**
     * Create an instance of {@link DerivedProperty1Entity1Threat }
     * 
     */
    public DerivedProperty1Entity1Threat createDerivedProperty1Entity1Threat() {
        return new DerivedProperty1Entity1Threat();
    }

    /**
     * Create an instance of {@link Relations2Entities }
     * 
     */
    public Relations2Entities createRelations2Entities() {
        return new Relations2Entities();
    }

    /**
     * Create an instance of {@link Relation2Entities }
     * 
     */
    public Relation2Entities createRelation2Entities() {
        return new Relation2Entities();
    }

    /**
     * Create an instance of {@link DerivedProperties1Entity }
     * 
     */
    public DerivedProperties1Entity createDerivedProperties1Entity() {
        return new DerivedProperties1Entity();
    }

    /**
     * Create an instance of {@link DerivedProperty1Entity }
     * 
     */
    public DerivedProperty1Entity createDerivedProperty1Entity() {
        return new DerivedProperty1Entity();
    }

    /**
     * Create an instance of {@link Relations1Entity1Threat }
     * 
     */
    public Relations1Entity1Threat createRelations1Entity1Threat() {
        return new Relations1Entity1Threat();
    }

    /**
     * Create an instance of {@link Relation1Entity1Threat }
     * 
     */
    public Relation1Entity1Threat createRelation1Entity1Threat() {
        return new Relation1Entity1Threat();
    }

    /**
     * Create an instance of {@link Relationships }
     * 
     */
    public Relationships createRelationships() {
        return new Relationships();
    }

    /**
     * Create an instance of {@link System }
     * 
     */
    public System createSystem() {
        return new System();
    }

    /**
     * Create an instance of {@link Entities }
     * 
     */
    public Entities createEntities() {
        return new Entities();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link DerivedProperties1Entity1Threat }
     * 
     */
    public DerivedProperties1Entity1Threat createDerivedProperties1Entity1Threat() {
        return new DerivedProperties1Entity1Threat();
    }

    /**
     * Create an instance of {@link Properties1Entity }
     * 
     */
    public Properties1Entity createProperties1Entity() {
        return new Properties1Entity();
    }

    /**
     * Create an instance of {@link Threats }
     * 
     */
    public Threats createThreats() {
        return new Threats();
    }

    /**
     * Create an instance of {@link Threat }
     * 
     */
    public Threat createThreat() {
        return new Threat();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

}
