//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.01 at 04:03:41 PM CEST 
//


package it.polito.dp2.TAMELESS.sol.service.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties1Entity" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="properties1Entity1Threat" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="self" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "properties1Entity",
    "properties1Entity1Threat",
    "self"
})
@XmlRootElement(name = "properties")
public class Properties {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String properties1Entity;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String properties1Entity1Threat;
    @XmlSchemaType(name = "anyURI")
    protected String self;

    /**
     * Gets the value of the properties1Entity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperties1Entity() {
        return properties1Entity;
    }

    /**
     * Sets the value of the properties1Entity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperties1Entity(String value) {
        this.properties1Entity = value;
    }

    /**
     * Gets the value of the properties1Entity1Threat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperties1Entity1Threat() {
        return properties1Entity1Threat;
    }

    /**
     * Sets the value of the properties1Entity1Threat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperties1Entity1Threat(String value) {
        this.properties1Entity1Threat = value;
    }

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelf(String value) {
        this.self = value;
    }

}
