//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.01 at 04:03:41 PM CEST 
//


package it.polito.dp2.TAMELESS.sol.service.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="relations2Entities" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="relations3Entities" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="relations2Entities1Threat" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="relations1Entity1Threat" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="self" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "relations2Entities",
    "relations3Entities",
    "relations2Entities1Threat",
    "relations1Entity1Threat",
    "self"
})
@XmlRootElement(name = "relationships")
public class Relationships {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String relations2Entities;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String relations3Entities;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String relations2Entities1Threat;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String relations1Entity1Threat;
    @XmlSchemaType(name = "anyURI")
    protected String self;

    /**
     * Gets the value of the relations2Entities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelations2Entities() {
        return relations2Entities;
    }

    /**
     * Sets the value of the relations2Entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelations2Entities(String value) {
        this.relations2Entities = value;
    }

    /**
     * Gets the value of the relations3Entities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelations3Entities() {
        return relations3Entities;
    }

    /**
     * Sets the value of the relations3Entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelations3Entities(String value) {
        this.relations3Entities = value;
    }

    /**
     * Gets the value of the relations2Entities1Threat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelations2Entities1Threat() {
        return relations2Entities1Threat;
    }

    /**
     * Sets the value of the relations2Entities1Threat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelations2Entities1Threat(String value) {
        this.relations2Entities1Threat = value;
    }

    /**
     * Gets the value of the relations1Entity1Threat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelations1Entity1Threat() {
        return relations1Entity1Threat;
    }

    /**
     * Sets the value of the relations1Entity1Threat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelations1Entity1Threat(String value) {
        this.relations1Entity1Threat = value;
    }

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelf(String value) {
        this.self = value;
    }

}
