//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.01 at 04:03:41 PM CEST 
//


package it.polito.dp2.TAMELESS.sol.service.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entities" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="threats" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="relationships" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="properties" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="results" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="self" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entities",
    "threats",
    "relationships",
    "properties",
    "results",
    "self"
})
@XmlRootElement(name = "system")
public class System {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String entities;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String threats;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String relationships;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String properties;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String results;
    @XmlSchemaType(name = "anyURI")
    protected String self;

    /**
     * Gets the value of the entities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntities(String value) {
        this.entities = value;
    }

    /**
     * Gets the value of the threats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreats() {
        return threats;
    }

    /**
     * Sets the value of the threats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreats(String value) {
        this.threats = value;
    }

    /**
     * Gets the value of the relationships property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationships() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationships(String value) {
        this.relationships = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperties(String value) {
        this.properties = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResults(String value) {
        this.results = value;
    }

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelf(String value) {
        this.self = value;
    }

}
