//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.01 at 04:03:41 PM CEST 
//


package it.polito.dp2.TAMELESS.sol.neo4j.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.TAMELESS.sol.neo4j.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.TAMELESS.sol.neo4j.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link CypherResponse }
     * 
     */
    public CypherResponse createCypherResponse() {
        return new CypherResponse();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Results.Data }
     * 
     */
    public Results.Data createResultsData() {
        return new Results.Data();
    }

    /**
     * Create an instance of {@link CypherResponse.Errors }
     * 
     */
    public CypherResponse.Errors createCypherResponseErrors() {
        return new CypherResponse.Errors();
    }

    /**
     * Create an instance of {@link UniquenessBody }
     * 
     */
    public UniquenessBody createUniquenessBody() {
        return new UniquenessBody();
    }

    /**
     * Create an instance of {@link it.polito.dp2.TAMELESS.sol.neo4j.jaxb.Data }
     * 
     */
    public it.polito.dp2.TAMELESS.sol.neo4j.jaxb.Data createData() {
        return new it.polito.dp2.TAMELESS.sol.neo4j.jaxb.Data();
    }

    /**
     * Create an instance of {@link CypherRequest }
     * 
     */
    public CypherRequest createCypherRequest() {
        return new CypherRequest();
    }

    /**
     * Create an instance of {@link Statements }
     * 
     */
    public Statements createStatements() {
        return new Statements();
    }

    /**
     * Create an instance of {@link RelationshipResponseType }
     * 
     */
    public RelationshipResponseType createRelationshipResponseType() {
        return new RelationshipResponseType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

}
